ALTER TABLE platform_admins
  ADD COLUMN platform_role_id INT NULL AFTER id;

ALTER TABLE users
  ADD COLUMN merchant_role_id INT NULL AFTER branch_id;

CREATE TABLE IF NOT EXISTS platform_admin_photos (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  platform_admin_id INT NOT NULL,
  url TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_platform_admin_photos_admin
    FOREIGN KEY (platform_admin_id) REFERENCES platform_admins(id)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_photos (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  url TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_user_photos_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE CASCADE
);
